### ISSUE TITLE
Make me a maintainer?

### ISSUE THREAD

**Issue by ndarilek** [darbaga/Tolk-rs#5]
Hello,

I'm actively using this crate in a [couple](https://github.com/ndarilek/tts-rs) [places](https://github.com/lightsoutgames/godot-tts). It's powering the screen reader support in a cross-platform audio game I'm writing, and I'm using it at the core of some game accessibility plugins where no screen reader can currently run. Thanks for your work!

I submitted my recent PR because my players were encountering some odd string issues where binary data was spoken, or where strings were cut off. Replacing your custom string-handling with the widestring crate seems to have resolved that. Now I'd like to push a 0.2.1 build and update my crate dependencies.

Additionally, I'm hitting some other link errors using this crate with others. I'd like to try resolving those for future releases.

Would you mind making me a maintainer both here and on crates.io? I'm happy to keep pushing to your repo if that's OK. This is a small crate, so I don't imagine having to make lots and lots of changes. But it would be helpful if I could turn around releases quickly so my upstream crates can benefit.

And again, thanks for this work. It got me up and running with TTS more quickly under Windows, and both I and my players appreciate that screen readers are a supported TTS option.

**Comment by darbaga** [comment]
Hi,

That seems good to me. I added you to this (and tolk-sys) both here and on crates.io. If you need to use your own repositories for the crates, let me know, and we can figure something out (you shouldn't need to, however).

I'm glad this was helpful. Honestly this was mostly just a Rust learning project for me, so it's really nice to know people have been using it.

**Comment by ndarilek** [comment]
Thank you! Pushed the new crate and propagating out to dependencies now.
